version: '3.8'

services:
  # MySQL Service
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: greenSpacedb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "8099:80"
    depends_on:
      - mysql
    networks:
      - mynetwork

  # Your Project Service (Java application with Docker)
  myproject:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: greenspace
    ports:
       - "8089:8089" 
    depends_on:
      - mysql
    networks:
      - mynetwork

volumes:
  mysql-data:

networks:
  mynetwork:
    driver: bridge
